---
- name: Check for the Laravel Helpers
  lineinfile:
    dest: "/home/{{ dotfiles_user }}/.profile"
    regexp: "(?i)^# *Laravel Helpers"
    line: "# Laravel Helpers"
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_group }}"
    create: yes
    backup: yes
    state: present

- name: Add the Laravel Helpers
  lineinfile:
    dest: "/home/{{ dotfiles_user }}/.profile"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
    state: present
  with_items: dotfiles_laravel_helpers
